# 测试环境环境配置

server:
  # 服务端口
  port: 5000

logging:
  level:
    # SQL日志记录
    io.github.talelin.latticy.mapper: debug

spring:
  # h2 内存数据库配置，供测试使用，其它环境勿用
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: '17605259250'
    url: jdbc:mysql://jokky.fun:3306/lin-cms?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    username: root

# 开启权限拦截
auth:
  enabled: true


# 开启http请求日志记录
request-log:
  enabled: true
